/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class getAutographPoint_GetAutoGraphNative */

#ifndef _Included_getAutographPoint_GetAutoGraphNative
#define _Included_getAutographPoint_GetAutoGraphNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     getAutographPoint_GetAutoGraphNative
 * Method:    getAutographPoint
 * Signature: (Ljava/lang/String;)[LgetAutographPoint/Result;
 */
JNIEXPORT jobjectArray JNICALL Java_getAutographPoint_GetAutoGraphNative_getAutographPoint
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
