/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeAPI */

#ifndef _Included_NativeAPI
#define _Included_NativeAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeAPI
 * Method:    getAutographPoint
 * Signature: (Ljava/lang/String;)[LResult;
 */
JNIEXPORT jobjectArray JNICALL Java_NativeAPI_getAutographPoint
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
